### PR TITLE
🚨 upgrade to curvenote config 🚨

### PR DESCRIPTION
**Pull request by stevejpurves**
This PR upgrades the `curvenote.yml` config and project layout to `v1` from `alpha`. This change will fix currently deployed sites which will return a 500 until this PR is merged and deployed.

This was a breaking change, all future upgrades will be backwards compatible.

### CODE REVIEW

**Comment by stevejpurves** [comment]
@johnjarmitage sorry but we just deployed some big changes that broke currently deployed sites. This is a big upgrade, and we should not have this problem again in future.

You should also update your local curvenote client to the latest `npm install curvenote@latest`, that should get you `v0.15.0`

**Comment by stevejpurves** [comment]
the deployed site is actually now migrated, but this should still be merged

**Comment by johnjarmitage** [comment]
Thanks Steve !

**Comment by johnjarmitage** [comment]
Hi Steve, I broke something in trying to put the logo back in the page. I get the message "Article was not found" on the curve.space. I did a git revert to recover the logo and then tried to return curvenote.yml back to the new version. I think I deleted something else in the process...

**Comment by stevejpurves** [comment]
Let me take a look @johnjarmitage

**Pull request merged**
